<?php include('header.phtml');?>
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Dashboard</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
              <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
              <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
            </div>
            <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
              <span data-feather="calendar"></span>
              This week
            </button>
          </div>
        </div>

        <h2>All Users</h2>
        <div class="table-responsive">
          <table class="table table-striped table-sm">
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">User Status</th>
                <th scope="col">Change Status</th>
                <th scope="col">Delete Records</th>
              </tr>
            </thead>
            <tbody>
              <?php
              $a = '';
              foreach ($data as $user) {
                $a .= ("<tr><td>" . $user->id . "</td><td>" . $user->firstname . "</td><td>" . $user->lastname . "</td><td>" . $user->email . "</td><td>" . $user->status . "</td><td><form method='POST' action='customer'><input type='hidden' name='change' value=" . $user->id . " /><input type='submit' name='changestatus' value='change' /></form></td><td><form method='POST' action='customer'><input type='hidden' name='id' value=" . $user->id . " /><input type='submit' name='delete' value='Delete' /></form></td></tr>");
              }
              echo $a;
              //   foreach ($ss as $s) {
              //     echo $s;
              //   }
              ?>
            </tbody>
          </table>
        </div>
        <form method="POST" action="adduser">
          <input type="submit" value="Add New User" name="add" />
        </form>
      </main>
    </div>
  </div>


  <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>