<?php include('header.phtml');?>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Dashboard</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
              <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
              <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
            </div>
            <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
              <span data-feather="calendar"></span>
              This week
            </button>
          </div>
        </div>

        <h2>All Orders</h2>
        <div class="table-responsive">
          <table class="table table-striped table-sm">
            <thead>
              <tr>
                <th scope="col">Order ID</th>
                <th scope="col">User ID</th>
                <th scope="col">P_Details</th>
                <th scope="col">Product Status</th>
                <th scope="col">Change Status</th>

              </tr>
            </thead>
            <tbody>
              <?php
              $a = '';
              foreach ($data as $user) {

                $a .= ("<tr><td>" . $user->orderid . "</td><td>" . $user->userid . "</td><td>" . $user->pdetails . "</td><td>" . $user->pstatus . "</td><td><form method='POST' action='orders'><input type='hidden' name='change' value=" . $user->orderid . " /><input type='submit' name='changestatus' value='Change' /></form></td></tr>");
              }
              echo $a;
              ?>
            </tbody>
          </table>
        </div>

      </main>
    </div>
  </div>


  <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>