<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.88.1">
  <title>Dashboard Template · Bootstrap v5.1</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">



  <!-- Bootstrap core CSS -->
  <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    #inputEmail4 {
      pointer-events: none;
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="./assets/css/dashboard.css" rel="stylesheet">
</head>

<body>

  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <div class="navbar-nav">
      <div class="nav-item text-nowrap">
        <a class="nav-link px-3" href="login.php" name="signout">Sign out</a>
      </div>
    </div>
  </header>

  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="dashboard">
                <span data-feather="home"></span>
                Dashboard
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="orders">
                <span data-feather="file"></span>
                Orders
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="products">
                <span data-feather="shopping-cart"></span>
                Products
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="customer">
                <span data-feather="users"></span>
                Customers
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="bar-chart-2"></span>
                Reports
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="products">
                <span data-feather="layers"></span>
                Edit Product
              </a>
            </li>
          </ul>
        </div>
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2">Edit Product</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
              <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
              <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
            </div>
            <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
              <span data-feather="calendar"></span>
              This week
            </button>
          </div>
        </div>

        <form class="row g-3" method="POST" enctype="multipart/form-data" action='updateproduct'>
          <div class="col-md-6">
            <label for="inputEmail4" class="form-label">ID</label>
            <input type="text" class="form-control" name="pid" id="inputEmail4" value=<?php echo $data[0]->id ?>>
          </div>
          <div class="col-md-6">
            <label for="inputPassword4" class="form-label">Name</label>
            <input type="text" class="form-control" name="pname" id="inputPassword4" value=<?php echo $data[0]->pname ?>>
          </div>
          <div class="col-12">
            <label for="inputAddress" class="form-label">Product Category</label>
            <input type="text" class="form-control" id="inputAddress" name="pcategory" placeholder="Category" value=<?php echo $data[0]->pcategory ?>>
          </div>
          <div class="col-12">
            <label for="inputAddress2" class="form-label">Market Price</label>
            <input type="text" class="form-control" id="inputAddress2" name="price" placeholder="Price" value=<?php echo $data[0]->price ?>>
          </div>
          <div class="col-md-6">
            <label for="inputCity" class="form-label">Store Address with City</label>
            <input type="text" class="form-control" id="inputCity" name="city" value=<?php echo $data[0]->pcity ?>>
          </div>
          <div class="col-md-4">
            <label for="inputState" class="form-label">State</label>
            <input type="text" id="inputState" placeholder="State" class="form-control" name="state" value=<?php echo $data[0]->pstate ?>>

          </div>
          <div class="col-md-2">
            <label for="inputZip" class="form-label">Zip</label>
            <input type="text" class="form-control" id="inputZip" name="zip" value=<?php echo $data[0]->pzip ?>>
          </div>
          <div class="col-12">
            <div class="form-check">
              <input class="form-check-input" type="checkbox" id="gridCheck">
              <label class="form-check-label" for="gridCheck">
                Check me out
              </label>
            </div>
          </div>

          <div class="col-md-8">
         <img src="../../../public/images/<?php echo $data[0]->pimage?>" height="150" width = "150" alt="">
         <br>
          <label for="fieldImageFile" class="form-label">Upload your Image</label>
            <?php echo $this->tag->fileField(["product_image", "size" => 30, "class" => "form-control" , "id" => "fieldImageFile"]) ?>
          </div>
          <div class="col-12">
            <input type="submit" class="btn btn-primary" name="update" value="Update">

          </div>
        </form>
      </main>
    </div>
  </div>
  <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>