<?php
$var = $this->session;
$var = $this->container->getSession();
if (!$var->has('cart')) {
    header('Location:http://localhost:8080/user/shop');
}

$t = $var->get('cart');
$arr = array();
$arr = $t;
$temp = '';
$total = 0;
for ($i = 0; $i < count($arr); $i++) {
    $temp .= ' <li class="list-group-item d-flex justify-content-between lh-sm">
  <div>
    <h6 class="my-0">' . $t[$i]['name'] . '</h6>
    <small class="text-muted">Brief description</small>
  </div>
  <span class="text-muted">' . $t[$i]['price'] . '</span>
</li>';
    $total = $total + $t[$i]['price'] * $t[$i]['quantity'];
}
?>

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Checkout example · Bootstrap v5.1</title>


    <!-- Bootstrap core CSS -->
    <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>

<body class="bg-light">

    <div class="container">
        <main>
            <div class="py-5 text-center">
                <h2>Checkout form</h2>
                <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
            </div>

            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Your cart</span>
                        <span class="badge bg-primary rounded-pill"><?php echo count($_SESSION['cart']) ?></span>
                    </h4>
                    <ul class="list-group mb-3">

                        <?php
                        echo $temp;
                        ?>
                        <li class="list-group-item d-flex justify-content-between">
                            <?php
                            if (count($arr) != 0) {
                                echo "<span>Total (Rs)</span> <strong>" . $total . "</strong>";
                            }
                            ?>

                        </li>
                    </ul>

                    <form class="card p-2" method="POST">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Promo code">
                            <button type="submit" class="btn btn-secondary">Redeem</button>
                        </div>

                    </form>
                    <a href="shop" class="btn btn-danger">Go to Home Page</a>

                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Billing address</h4>
                    <form class="needs-validation" novalidate method="POST" action="checkout">
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for="firstName" class="form-label">First name</label>
                                <input type="text" class="form-control" id="firstName" placeholder="" value=<?php echo $_SESSION['userdata']['fname'] ?> required>
                                <div class="invalid-feedback">
                                    Valid first name is required.
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <label for="lastName" class="form-label">Last name</label>
                                <input type="text" class="form-control" id="lastName" placeholder="" value=<?php echo $_SESSION['userdata']['lname'] ?> required>
                                <div class="invalid-feedback">
                                    Valid last name is required.
                                </div>
                            </div>



                            <div class="col-12">
                                <label for="email" class="form-label">Email </label>
                                <input type="email" disabled class="form-control" id="email" value=<?php echo $_SESSION['userdata']['email'] ?> placeholder="you@example.com">
                                <div class="invalid-feedback">
                                    Please enter a valid email address for shipping updates.
                                </div>
                            </div>

                            <div class="col-12">
                                <label for="address" class="form-label">Address</label>
                                <input type="text" class="form-control" id="address" placeholder="1234 Main St" required>
                                <div class="invalid-feedback">
                                    Please enter your shipping address.
                                </div>
                            </div>


                        </div>

                        <hr class="my-4">

                        <input class="w-100 btn btn-primary btn-lg" type="submit" value="Place Order" name="check">
                    </form>
                </div>
            </div>
        </main>

        <footer class="my-5 pt-5 text-muted text-center text-small">
            <p class="mb-1">&copy; 2017–2021 Company Name</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Privacy</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Support</a></li>
            </ul>
        </footer>
    </div>


    <script src="../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="./assets/js/form-validation.js"></script>
</body>

</html>